name = "TerraPerkaCraft"
author = "Raws"
version = "3.0.0+1.21.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "77f7dc0306e966ad8ca4252ad564bd4e667035ca14e07f59c8d18f52e046b8b1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
