name = "TerraPerkaCraft"
author = "Raws"
version = "1.0.0+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4346e7f4ca442cff72a1c6754cdb841c5a0f2b541082a48ba76caf2b52b16839"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
