name = "TerraPerkaCraft"
author = "Raws"
version = "2.0.0+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6934731ae3c0bb7c2e33d5a8db10bd7d09e2f30da17c86027a7182a1f2250d5e"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
