name = "TerraPerkaCraft"
author = "Raws"
version = "3.0.0+1.21.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "09dcca3410aebaad067314e4c49e7d7054b6f2ddb4956b04c37ee192267d34e6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
