name = "TerraPerkaCraft"
author = "Raws"
version = "0.0.1+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "39cfd4caa92867dc0d12115d222ea32854c1093b85c177fa3584d2f9f512a624"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
