name = "TerraPerkaCraft"
author = "Raws"
version = "1.0.0+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9d0fdd3431dd9d8732100ebd7d45cfe3db34886888e4f956fd6cdce3135653af"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
