name = "TerraPerkaCraft"
author = "Raws"
version = "2.0.0+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b2bd2c2cf6d19a743bfa3b39fd1f30dc1e83e928169bbf4663a7dc840be1fda4"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
