name = "TerraPerkaCraft"
author = "Raws"
version = "1.0.0+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c4d4d18b458054d4fdd945a76e3ff011fbd3118bd68d9eaa764332fb87141089"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
