name = "Perkpack 4"
author = "Raws"
version = "0.0.1+1.21"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fdb397805af9b2abf059756b121786f510cb3c537fc414cfa098ce7196754474"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
