name = "Perkpack 4"
author = "Raws"
version = "0.0.1+1.21"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93f075dca6a0797bff1c5c2922410c7108ac50688b4d76ea843e2542e01b7ba5"

[versions]
fabric = "0.16.5"
minecraft = "1.21"

[options]
acceptable-game-versions = ["1.19.2"]
