name = "Perkpack 4"
author = "Raws"
version = "0.0.1+1.21"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d80ad2a738131879ad2f03a19d2a2d3d601aeb989f5e1cc662289f0106054015"

[versions]
fabric = "0.16.5"
minecraft = "1.21"
