name = "Perkpack 4"
author = "Raws"
version = "0.0.1+1.21"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "453566ed0cca0ecf2d27d71bb4123314fb60236bf9d18c0bca03257f512956f1"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
