name = "Perkpack 4"
author = "Raws"
version = "0.0.1+1.21"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c81ade8869c0a3d406ead65d8c0ca4d3ea5a0f9cd86db66c98b4a4bf977bc361"

[versions]
fabric = "0.16.5"
minecraft = "1.21"

[options]
acceptable-game-versions = ["1.19.2"]
