name = "Perkpack 4"
author = "Raws"
version = "0.0.1+1.21"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0dc652b91fd0893acbbae3adc12cedf60513d7f2b40c8f5e4fd18bf0694cd6ee"

[versions]
fabric = "0.16.5"
minecraft = "1.21"
