name = "Perkpack 4"
author = "Raws"
version = "0.0.1+1.21"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4d716a176f5d462776b6f390f6eb9a1378e4fc3184bcf192cf7c66b806b61721"

[versions]
fabric = "0.16.5"
minecraft = "1.21"
