require 'bundler/setup'
require 'archive/zip'
require 'aws-sdk-s3'
require 'cgi/util'
require 'digest/md5'
require 'json'
require 'octokit'

require 'mod_packs/mod'
require 'mod_packs/pack'
require 'mod_packs/package'
require 'mod_packs/client_package'
require 'mod_packs/curseforge_client_package'
require 'mod_packs/generic_client_package'
require 'mod_packs/release'
require 'mod_packs/server_package'
