
[general]
	#If true (default), the daylight cycle will not start until the first player joins the world. Handy for multiplayer and/or heavy modpacks.
	delayTimeCycleUntilFirstJoin = true
	#If true (NOT default), doDaylightCycle will be forced to false when the server/world is empty. Might be useful for multiplayer.
	disableTimeCycleWhenServerEmpty = true
	#Start time in ticks to use the day multiplier. 0 represents a standard Minecraft day start of 06:00. Must be less than nightStartInTicks.
	#Range: 0 ~ 2147482646
	dayStartInTicks = 0
	#Multiply the day length by this number. Fractions are supported, but must be above 1.0 (cannot shorten).
	#Range: 1.0 ~ 100.0
	dayLengthMultiplier = 3.0
	#Start time in ticks to use the night multiplier. 13000 represents a standard Minecraft night start of 19:00.
	#Range: 1 ~ 2147482647
	nightStartInTicks = 13000
	#Multiply the night length by this number. Fractions supported, but must be above 1.0 (cannot shorten).
	#Range: 1.0 ~ 100.0
	nightLengthMultiplier = 3.0
