services:
  caddy: # An HTTP server to serve Packwiz files locally
    image: caddy
    ports:
      - '8082:80'
    volumes:
      - 'caddy:/data'
      - '.:/usr/share/caddy'
  minecraft:
    image: itzg/minecraft-server
    depends_on:
      - caddy
    ports:
      - '25565:25565'
    volumes:
      - './tmp/server:/data'
    environment:
      ALLOW_FLIGHT: 'true'
      # DEBUG: 'true' # Uncomment for verbose logs from itzg/minecraft-server
      DIFFICULTY: hard
      ENABLE_ROLLING_LOGS: 'true'
      EULA: 'true'
      FORGEVERSION: '43.2.0'
      ICON: http://caddy/images/scumco-dev-server-icon-64.png
      LEVEL_TYPE: 'minecraft:amplified'
      MEMORY: '4G'
      MODE: creative
      MOTD: 'ScumCo development server'
      OPS_FILE: https://s3.amazonaws.com/minecraft/allowlists/blolol.ops.json
      PACKWIZ_URL: http://caddy/pack.toml
      SPAWN_PROTECTION: 0
      TYPE: FORGE
      USE_AIKAR_FLAGS: 'true'
      VERSION: '1.19.2'
      VIEW_DISTANCE: 16
volumes:
  caddy:
