name = "Scumco"
author = "Raws"
version = "1.0.6+1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fad4fe1bd9f866eb3d0e291e51e9eaaf34200c2bb518b3c52a57a8bd2c09757b"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
