name = "Scumco"
author = "Raws"
version = "1.0.2+1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "704e09add9f95646e6deda7a6d6a9b5766aba60948870e8614cdadfef9bc32b5"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
