name = "ScumCo"
author = "Raws"
version = "1.1.0+1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f53d5a7af4a6fe896aa5e69238e04f75b3d719fd7f85e8106a2268ddf2caf50"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
