name = "Scumco"
author = "Raws"
version = "1.0.3+1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4cffce6c47361f2ef0c7ee3fa1609d0ccdb91a896df9b6f4e3002d1ddfb6346f"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
