name = "Scumco"
author = "Raws"
version = "1.0.0-pre1+1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c76d9401f69f9b06c37b3ba597ab75867f57b4b3335607ae5915bdf3d9eb7c6b"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
