name = "ScumCo"
author = "Raws"
version = "1.0.7+1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a94ea4b0bc215e0806fb3b48c314c47d443781e33414d2481ad770d092b7c99"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
