services:
  caddy: # An HTTP server to serve Packwiz files locally
    image: caddy
    ports:
      - '8082:80'
    volumes:
      - 'caddy:/data'
      - '.:/usr/share/caddy'
  minecraft:
    image: itzg/minecraft-server
    depends_on:
      - caddy
    ports:
      - '8100:8100' # BlueMap web server
      - '25565:25565'
    volumes:
      - './tmp/server:/data'
    environment:
      ALLOW_FLIGHT: 'true'
      # DEBUG: 'true' # Uncomment for verbose logs from itzg/minecraft-server
      DIFFICULTY: hard
      ENABLE_ROLLING_LOGS: 'true'
      EULA: 'true'
      ICON: http://caddy/images/perkpack-dev-64.png
      MEMORY: '4G'
      MODE: creative
      MOTD: 'Perkpack development server'
      OPS_FILE: https://s3.amazonaws.com/minecraft/allowlists/blolol.ops.json
      PACKWIZ_URL: http://caddy/pack.toml
      SPAWN_PROTECTION: 0
      TYPE: QUILT
      QUILT_LOADER_VERSION: '0.25.0'
      USE_AIKAR_FLAGS: 'true'
      VERSION: '1.20.1'
      VIEW_DISTANCE: 32
volumes:
  caddy:
