name = "Perkpack"
author = "Raws"
version = "3.10.1+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "412e446b5fe3e0d2f49748c9d3caee9db34a4c14cf3117ad1d61eda6f114d483"

[versions]
minecraft = "1.20.1"
quilt = "0.25.0"
