name = "Perkpack"
author = "Raws"
version = "3.0.0-pre1+1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e8ac89968a1966faca094d0e3751e6163f4247e4dcae38e1e6dfb77ab9c32396"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.53"
