name = "Perkpack"
author = "Raws"
version = "3.0.0-pre1+1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "099fe7189592c28b2d92dd8e491eeb87cffd23f3463db6167fdda94bb38bbd77"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.53"
