name = "Perkpack"
author = "Raws"
version = "3.1.0+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f9f5a2c96bdd0eb0604c808cbbfe37243e8cd974ef7760b4adeeba821122e0f2"

[versions]
minecraft = "1.20.1"
quilt = "0.20.2"
