name = "Perkpack"
author = "Raws"
version = "3.14.0+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "033465ee4172e8c7cd0a3538d9c6dbe091b1e9272192daa44f7d4053da13d54e"

[versions]
minecraft = "1.20.1"
quilt = "0.25.0"
