name = "Perkpack"
author = "Raws"
version = "3.0.0-pre3+1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "688061dfe8d1a0878005780bfcb8f66721054ba31b5b9e56719190d94eddecbd"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.53"
