name = "Perkpack"
author = "Raws"
version = "3.15.0+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dbb82df5fb24b5f8d556022f4f70c206a6a9a3daa9a6475b104b699fbd43aaf4"

[versions]
minecraft = "1.20.1"
quilt = "0.25.0"
