name = "Perkpack"
author = "Raws"
version = "2.0.0-pre9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f853929e1318ea8dc09decb0dca3bbea6d30c4bd70af5acfecc750ede1eab1ff"

[versions]
forge = "40.1.57"
minecraft = "1.18.2"
