name = "Perkpack"
author = "Raws"
version = "3.2.0+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d95732885cf33312b7a243fa9a1d16007d529bffb09e1c6a3b9168b9804120e6"

[versions]
minecraft = "1.20.1"
quilt = "0.20.2"
