name = "Perkpack"
author = "Raws"
version = "3.9.0+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4dcaa63cc3719fd086dab273436b14d4d7e71230631109af6c3941d9f7b891a8"

[versions]
minecraft = "1.20.1"
quilt = "0.25.0"
