name = "Perkpack"
author = "Raws"
version = "3.0.0-pre4+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "784bca87bc78f2a160e5ef3f5362bde8cf40fed3abf3e696877546ca630160cc"

[versions]
minecraft = "1.20.1"
quilt = "0.20.2"
