name = "Perkpack"
author = "Raws"
version = "3.2.0+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f9bc9d328d45fd7f1253273ca3e3573265dc665c445b7f040c42989d6e8bf099"

[versions]
minecraft = "1.20.1"
quilt = "0.20.2"
