name = "Perkpack"
author = "Raws"
version = "3.0.0+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "853133aaba1d85579f773ee98c2072be0acca530eb46c4fe70ba104a392ca80f"

[versions]
minecraft = "1.20.1"
quilt = "0.20.2"
