name = "Perkpack"
author = "Raws"
version = "3.4.0+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e87d759d6d3b9c119adbd4363fb752b4a15868549810745fb365aecaa4dfa15"

[versions]
minecraft = "1.20.1"
quilt = "0.20.2"
