name = "Perkpack"
author = "Raws"
version = "2.0.0-pre11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aedf8bb422cb290665774d8eb132e200b03ad92068d59ad61963ad47a24de8fd"

[versions]
forge = "40.1.57"
minecraft = "1.18.2"
