name = "Perkpack"
author = "Raws"
version = "3.4.0+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bdc5bcf773d2f6ce2dcf7bcc2c2f7ba0750c89eed82712132632441d06043150"

[versions]
minecraft = "1.20.1"
quilt = "0.20.2"
