name = "Perkpack"
author = "Raws"
version = "2.0.0-pre3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "29aace67889cab968d32bdd7eb824bedb97cd081953eeaccd1820685f1094fc9"

[versions]
forge = "40.1.57"
minecraft = "1.18.2"
