name = "Perkpack"
author = "Raws"
version = "3.10.1+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9c61b7f4ccaa534a3bca68975d7175b8bfaf1d5bf1a40e24c36f650a6e2af370"

[versions]
minecraft = "1.20.1"
quilt = "0.25.0"
