name = "Perkpack"
author = "Raws"
version = "3.10.0+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "41574e914db07b5f4fc91f13dd133c88cfce39651f704b78bdf2581f1d42165e"

[versions]
minecraft = "1.20.1"
quilt = "0.25.0"
