name = "Perkpack"
author = "Raws"
version = "2.0.0-pre19"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "22688bd3243dbd19d113b7e8b63096f633eaf113f714706434fde21193ca993d"

[versions]
forge = "40.1.57"
minecraft = "1.18.2"
