name = "Perkpack"
author = "Raws"
version = "3.1.0+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "335aa76cff284259f375c4ca79a42bd9f9fe7c64e45cd46987bfbb1bca778a6e"

[versions]
minecraft = "1.20.1"
quilt = "0.20.2"
