name = "Perkpack"
author = "Raws"
version = "3.0.0-pre1+1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b61b3e1f85aa15e70b8a8f05eaa1427d4b33ffab1a314b38d966dd39a8232b79"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.53"
