name = "Perkpack"
author = "Raws"
version = "2.0.0-pre4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d9556e0e5698281b417dca9f2d0f3ae13cddd605ad859f0214b222961a4f6a37"

[versions]
forge = "40.1.57"
minecraft = "1.18.2"
