name = "Perkpack"
author = "Raws"
version = "3.0.0-pre4+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a3a0d1790ea3cd6e879510e905491cdb5015c4460edb537c7d45ff8e88046def"

[versions]
minecraft = "1.20.1"
quilt = "0.20.2"
