name = "Perkpack"
author = "Raws"
version = "3.3.0+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "569e4d42103acf8cc58f1246f6eeddd87473aa1a43eead6a9816b80aae72f643"

[versions]
minecraft = "1.20.1"
quilt = "0.20.2"
