name = "Perkpack"
author = "Raws"
version = "3.2.0+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "072a9f9f1b86480ed075e300f5c7c8786d8bf9969373c7f7acb613eb4769661a"

[versions]
minecraft = "1.20.1"
quilt = "0.20.2"
