name = "Perkpack"
author = "Raws"
version = "3.3.0+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "769d4d83fe36acfe8b780e8b2656768cb8155936340ba73f48d44cf1931f18f6"

[versions]
minecraft = "1.20.1"
quilt = "0.20.2"
