name = "Perkpack"
author = "Raws"
version = "2.0.0-pre4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a1cf16973d2265aba52f31f88703e554196b15de021575d52cb334e077c4b31"

[versions]
forge = "40.1.57"
minecraft = "1.18.2"
