name = "Perkpack"
author = "Raws"
version = "3.3.0+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4bc7954c384816b2f032d0d532003845788ef491c0f7aed27cd93b7ead6277e6"

[versions]
minecraft = "1.20.1"
quilt = "0.20.2"
