name = "Perkpack"
author = "Raws"
version = "2.0.0-pre7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "81da7e83839e0f1c76fb08c16acb5c67ed651b27862e779fde0a96c389ec13ee"

[versions]
forge = "40.1.57"
minecraft = "1.18.2"
