name = "Perkpack"
author = "Raws"
version = "3.0.0-pre3+1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7843c7ad8d6e340e7a19704e65091d5c1feb4b710f423c67b3608e3bd89eaa2c"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.53"
