name = "Perkpack"
author = "Raws"
version = "2.0.0-pre21"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b41a32516a5f8cf796f7bd1302311e44d437d66c829b7306cb1953f236c354ca"

[versions]
forge = "40.1.74"
minecraft = "1.18.2"
