name = "Perkpack"
author = "Raws"
version = "3.0.0-pre1+1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fdf94d41d9a8fad9a67da49d86d9282dbb8c77264727eb3881c8fdfaa9df97da"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.53"
