name = "Perkpack"
author = "Raws"
version = "3.13.0+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "61acfd1cda8e33946a818f68d6ec6a38887ed409596aeaea1f337d6aa97e60f8"

[versions]
minecraft = "1.20.1"
quilt = "0.25.0"
