name = "Perkpack"
author = "Raws"
version = "3.14.0+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c0a194bfe63ec9794cc82de670c79f3a20f5779b2345740985ee768209ccffa5"

[versions]
minecraft = "1.20.1"
quilt = "0.25.0"
