name = "Perkpack"
author = "Raws"
version = "3.0.0-pre1+1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ec8f9d9fbf7bba46dfc56be5eefe4e56b667ef79d0827919eac03e42d5c660e2"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.53"
