name = "Perkpack"
author = "Raws"
version = "3.4.0+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "88839b0af76b90f3fdf3c7b2945c428318e4d3f795c46db9576c97f7a104f8a3"

[versions]
minecraft = "1.20.1"
quilt = "0.20.2"
