name = "Perkpack"
author = "Raws"
version = "3.6.0+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "47a6baa6738aea4d3057406bb8e0d78cbde8d557f4862258ec8f79c34723c661"

[versions]
minecraft = "1.20.1"
quilt = "0.20.2"
