name = "Perkpack"
author = "Raws"
version = "2.0.0-pre21"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c45ec210d1b3210cb447152331499b7c20002bf0dc1746d92ae2e781929f0cc"

[versions]
forge = "40.1.74"
minecraft = "1.18.2"
