name = "Perkpack"
author = "Raws"
version = "2.0.0-pre6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "abfd500a32eb3d741af63624b0cd89f283e8d53ae83a6dff3f0f6cc6adf4619a"

[versions]
forge = "40.1.57"
minecraft = "1.18.2"
