name = "Perkpack"
author = "Raws"
version = "3.9.0+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a9d0e36b056bf6c22f8a209f84b102ae622633e58787f2a7cd71bd22f6704a91"

[versions]
minecraft = "1.20.1"
quilt = "0.25.0"
