name = "Perkpack"
author = "Raws"
version = "2.0.0-pre1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4f7fc5393ac82db77930fab8bc506d91d6d602853f8df3e1aada4a8dc80801b7"

[versions]
forge = "40.1.57"
minecraft = "1.18.2"
