name = "Perkpack"
author = "Raws"
version = "3.5.0+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "73c1a8d465a00d5756b377ee8b9220bc61029da42b8d1343b0d151444a1d746b"

[versions]
minecraft = "1.20.1"
quilt = "0.20.2"
