name = "Perkpack"
author = "Raws"
version = "2.0.0-pre11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "41d96fe1a4286e0f372fd2646010b039cb08cdf4a10afb0cbec7b6cd6190f5ba"

[versions]
forge = "40.1.57"
minecraft = "1.18.2"
