name = "Perkpack"
author = "Raws"
version = "3.9.0+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb2896d1537867630da49f730e3710b4113fd0ea05450b2e76622a803dffbd57"

[versions]
minecraft = "1.20.1"
quilt = "0.25.0"
