name = "Perkpack"
author = "Raws"
version = "3.11.0+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f0b6a637ae5bf050c093d7b8f4f83977b58685f6a30d71ebea90a8f46484c582"

[versions]
minecraft = "1.20.1"
quilt = "0.25.0"
