name = "Perkpack"
author = "Raws"
version = "2.0.0-pre14"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "19d470a24e727251b6ebd431d9d3f1fe40dcd4a64e769f9fb7c5c363bd1509c8"

[versions]
forge = "40.1.57"
minecraft = "1.18.2"
