name = "Perkpack"
author = "Ross Paffett"
version = "5.0.0-pre0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4400fb0f5f7d393c8383a0d15b319db67330b6039df64fae86387860641718f2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
