name = "Perkpack"
author = "Ross Paffett"
version = "5.0.0-pre0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c86a9c39a14c92ddb002e2f3e6e93f6e14ebb745bff3ff9870647e6495942287"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
