name = "Perkpack"
author = "Ross Paffett"
version = "5.0.0-pre0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c9dcef2cbd62ebc35d8be5d71b5561ed4596bdb9e551cf5d26e0ce8adf5bec1e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
