name = "Murderhole"
author = "Raws"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d682ad646677030eea987617b742400e0793e8a075bde988cca5ce2b8ea306e"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
