name: Notify IRC of mod pack releases
on:
  release:
    types:
      - published
jobs:
  notify:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./.github/workflows/scripts
    steps:
      - name: Check out release tag
        uses: actions/checkout@v2
      - name: Notify IRC of release
        continue-on-error: true
        run: ./notify.sh
        shell: bash
        env:
          BLOLOL_API_KEY: ${{ secrets.BLOLOL_API_KEY }}
          BLOLOL_API_SECRET: ${{ secrets.BLOLOL_API_SECRET }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
