name: Release updated mod packs
on:
  push:
    tags: '*/*' # Match tags like "perkpack/4.0.1"
jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./.github/workflows/scripts
    steps:
      - name: Check out release tag
        uses: actions/checkout@v2
      - name: Draft GitHub release
        run: ./release.sh
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
