name: Release updated mod packs
on:
  push:
    tags: '*/*' # Match tags like "perkpack/1.0.0"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out release tag
        uses: actions/checkout@v2
      - name: Update packwiz files on S3
        uses: ItsKarma/aws-cli@v1.70.0
        with:
          args: s3 sync --delete --acl public-read "packs/${GITHUB_REF_NAME%%/*}" "s3://minecraft/mod-packs/${GITHUB_REF_NAME%%/*}/"
        # run: bundle exec rake "upload[${GITHUB_REF_NAME%%/*}]"
        # shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
